site_name: netlify-plugin-password-protection
title: Password Protection | Netlify Plugin
description: >- # this means to ignore newlines until "baseurl:"
  Encrypt your static html pages
baseurl: "" # the subpath of your site if applicable, e.g. /blog
# Compress CSS
sass:
  style: compressed
  sass_dir: _sass

# Include in processing (e.g. Netlify directives)
# Uncomment before use

include:
  - _redirects
  - .netlify

# Exclude from processing.
# The following items will not be processed.
exclude:
  - password_template.html
  - readme.md
  - LICENSE.txt
  - netlify.toml
  - rakefile.rb
  - Gemfile
  - Gemfile.lock
  - node_modules
  - dev-tools
  - package*.json
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
