[[plugins]]
  package = "netlify-plugin-password-protection"

  [plugins.inputs]
    instructions = "Password is <em>'cheesepizza'</em><br>(all this text is a config option)<br><small>Go ahead and view the source</small>"
