[[plugins]]
  package = "netlify-plugin-password-protection"

  [plugins.inputs]
    instructions = "The password is <em>'cheesepizza'</em><br>(and this text is a config option)<br><small>Go ahead and view the source</small>" # default
